src/java/database/service/impl/ReservationBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package database.service.impl;

import database.entities.ReservationE;
import database.entities.SubPlayersE;
import database.service.ReservationService;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.persistence.EntityManager;

/**
 *
 * @author mato
 */
@ManagedBean(name = "reservationService")
@SessionScoped
public class ReservationBean implements ReservationService {

    @ManagedProperty(value = "#{jpaResourceBean}")
    private JPAResourceBean jpaResourceBean;

    @Override
    public void createReservation(ReservationE reservation) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            em.getTransaction().begin();
            em.persist(reservation);
            em.getTransaction().commit();
        } finally {
            em.close();
        }
    }

    @Override
    public boolean deleteReservation(long reservationId) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            em.getTransaction().begin();
            ReservationE reservation = em.find(ReservationE.class, reservationId);
            em.remove(reservation);
            em.getTransaction().commit();
        } catch (Exception ex) {
            return false;
        } finally {
            em.close();
        }
        return true;
    }

    @Override
    public ReservationE getReservationById(long reservationId) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            return em.find(ReservationE.class, reservationId);
        } finally {
            em.close();
        }
    }

    @Override
    public List<ReservationE> getReservationsByResDate(Date date) {
        EntityManager em;
        if (jpaResourceBean != null) {
            em = jpaResourceBean.getEMF().createEntityManager();
        } else {
            em = new JPAResourceBean().getEMF().createEntityManager();
        }
        
        Calendar calendar = Calendar.getInstance();
        Calendar dateCalendar = Calendar.getInstance();
        dateCalendar.setTime(date);
        List<ReservationE> reservations = em.createQuery("SELECT r FROM ReservationE r").getResultList();
        List<ReservationE> reservationsByDate = new ArrayList<ReservationE>();
        
        for(ReservationE reservation : reservations){
            calendar.setTime(reservation.getStartDate());
            if((calendar.get(1) == dateCalendar.get(1)) && (calendar.get(2) == dateCalendar.get(2)) && (calendar.get(5) == dateCalendar.get(5))){
                reservationsByDate.add(reservation);
            }
        }
        return reservationsByDate;
    }

    @Override
    public void alterReqPlayers(long reservationId, int newReqPlayers) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            em.getTransaction().begin();
            ReservationE sportFacility = em.find(ReservationE.class, reservationId);
            sportFacility.setReqPlayers(newReqPlayers);
            em.getTransaction().commit();
        } finally {
            em.close();
        }
    }

    @Override
    public void alterStartTime(long reservationId, Date newStartTime) {
        ReservationE reservation;
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            em.getTransaction().begin();
            reservation = em.find(ReservationE.class, reservationId);
            reservation.setEndDate(newStartTime);
            em.getTransaction().commit();
            em.refresh(reservation);
        } finally {
            em.close();
        }
    }

    @Override
    public void alterEndTime(long reservationId, Date newEndTime) {
        ReservationE reservation;
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            em.getTransaction().begin();
            reservation = em.find(ReservationE.class, reservationId);
            reservation.setEndDate(newEndTime);
            em.getTransaction().commit();
            em.refresh(reservation);
        } finally {
            em.close();
        }
    }

    @Override
    public void alterReservDate(long reservationId, Date newReservDate) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            em.getTransaction().begin();
            ReservationE reservation = em.find(ReservationE.class, reservationId);
            reservation.setStartDate(newReservDate);
            em.getTransaction().commit();
        } finally {
            em.close();
        }
    }

    @Override
    public void alterSubPlayer(long reservationId, List<SubPlayersE> newSubPlayers) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try {
            em.getTransaction().begin();
            ReservationE sportFacility = em.find(ReservationE.class, reservationId);
            sportFacility.setSubPlayers(newSubPlayers);
            em.getTransaction().commit();
        } finally {
            em.close();
        }
    }

    @Override
    public List<ReservationE> getReservationsBySportId(long sportId) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return em.createQuery(
                "SELECT r FROM ReservationE r JOIN r.sport s WHERE s.id = :sportID")
                .setParameter("sportID", sportId)
                .getResultList();
    }

    @Override
    public ReservationE getReservationByEventID(String eventID) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return (ReservationE) em.createQuery(
                "SELECT r FROM ReservationE r WHERE r.id = :eventID")
                .setParameter("eventID", eventID)
                .getSingleResult();
    }

    @Override
    public List<ReservationE> getReservationsBySportFacilityId(long sportFacilityId) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        System.out.println("-----Dtabase getting reservations-----");

        return em.createQuery(
                "SELECT r FROM ReservationE r JOIN r.sportFacility s WHERE s.id = :sportfacilityID")
                .setParameter("sportfacilityID", sportFacilityId)
                .getResultList();
    }

    @Override
    public List<ReservationE> getReservations(int at, int max) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return em.createQuery(
                "SELECT r FROM ReservationE r")
                .setFirstResult(at)
                .setMaxResults(max)
                .getResultList();
    }

    @Override
    public Long countReservationsTotal() {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        Long a = (Long) em.createQuery(
                "SELECT count(r) FROM ReservationE r")
                .getSingleResult();

        if (a == null) {
            a = new Long(0);
        }

        return a;
    }

    @Override
    public List<ReservationE> getAllReservations() {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return em.createQuery(
                "SELECT r FROM ReservationE r")
                .getResultList();
    }

    @Override
    public List<ReservationE> getReservationsStartByTitle(String title) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return em.createQuery(
                "SELECT r FROM ReservationE r WHERE LOWER(r.title) LIKE :tit")
                .setParameter("tit", title.toLowerCase() + "%") //% predstavuje lubovolny retazec
                .getResultList();
    }

    @Override
    public List<ReservationE> getReservationsStartByUserEmail(String usermail) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return em.createQuery(
                "SELECT r FROM ReservationE r JOIN r.userE u WHERE LOWER(u.email) LIKE :usermail")
                .setParameter("usermail", usermail.toLowerCase() + "%") //% predstavuje lubovolny retazec
                .getResultList();
    }

    @Override
    public List<ReservationE> getReservationsStartBySportName(String sportName) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return em.createQuery(
                "SELECT r FROM ReservationE r JOIN r.sport s WHERE LOWER(s.name) LIKE :sportname")
                .setParameter("sportname", sportName.toLowerCase() + "%") //% predstavuje lubovolny retazec
                .getResultList();
    }

    @Override
    public List<ReservationE> getReservationsStartBySportFacilityName(String sfName) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();

        return em.createQuery(
                "SELECT r FROM ReservationE r JOIN r.sportFacility s WHERE LOWER(s.name) LIKE :sfname")
                .setParameter("sfname", sfName.toLowerCase() + "%") //% predstavuje lubovolny retazec
                .getResultList();
    }

    /**
     * @return the jpaResourceBean
     */
    public JPAResourceBean getJpaResourceBean() {
        return jpaResourceBean;
    }

    /**
     * @param jpaResourceBean the jpaResourceBean to set
     */
    public void setJpaResourceBean(JPAResourceBean jpaResourceBean) {
        this.jpaResourceBean = jpaResourceBean;
    }
}

src/java/database/service/impl/SportsBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package database.service.impl;

import database.entities.SportsE;
import database.service.SportsService;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.persistence.EntityManager;

/**
 *
 * @author mato
 */
@ManagedBean(name="sportsService")
@SessionScoped
public class SportsBean implements SportsService{
    @ManagedProperty(value="#{jpaResourceBean}")
    private JPAResourceBean jpaResourceBean;
    
    @Override
    public void createSport(SportsE sport) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try{
            em.getTransaction().begin();            
            em.persist(sport);
            em.getTransaction().commit();
        }finally{
            em.close();
        }
    }

    @Override
    public boolean deleteSport(long sportId) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try{
            em.getTransaction().begin();
            SportsE sport = em.find(SportsE.class, sportId);        
            em.remove(sport);
            em.getTransaction().commit();            
        }
        catch (Exception ex){
            return false;
        }
        finally{
            em.close();
        }
        return true;
    }

    @Override
    public SportsE getSportById(long sportId) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try{
            return em.find(SportsE.class, sportId);
        }
        finally{
            em.close();
        }
    }

    @Override
    public List<SportsE> getAllSports() {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();        
        return em.createQuery("SELECT s FROM SportsE s").getResultList();
    }

    @Override
    public void alterSportName(long sportId, String newName) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        try{
            em.getTransaction().begin();
            SportsE sport = em.find(SportsE.class, sportId);
            sport.setName(newName);
            em.getTransaction().commit();
        }finally{
            em.close();
        }
    }
    
    @Override
    public boolean existsSportWithName(String sportName) {
        EntityManager em = jpaResourceBean.getEMF().createEntityManager();
        
        Long a = (Long) em.createQuery(
            "SELECT count(s.name) FROM SportsE s WHERE s.name LIKE :sportname")
            .setParameter("sportname", sportName)      
            .setMaxResults(1)
            .getSingleResult();
        
        return  (a.longValue()==0) ? false : true;   
    }

    /**
     * @return the jpaResourceBean
     */
    public JPAResourceBean getJpaResourceBean() {
        return jpaResourceBean;
    }

    /**
     * @param jpaResourceBean the jpaResourceBean to set
     */
    public void setJpaResourceBean(JPAResourceBean jpaResourceBean) {
        this.jpaResourceBean = jpaResourceBean;
    }
    
}

src/java/managedBeans/SportFacilityBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBeans;

import database.entities.SportFacilityE;
import database.service.SportsFacilitiesService;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import utils.Sorting;

/**
 *
 * @author Gabo
 */
@ManagedBean(name="sportFacilityBean")
@SessionScoped
public class SportFacilityBean {
    private List<SportFacilityE> sportFacilities;
    private SportFacilityE selectedSportFacility;
    @ManagedProperty(value="#{sportsFacilitiesService}")
    private SportsFacilitiesService sportFacilitiyService;
        
    //Getters and Setters-------------------------------------------------------
    public List<SportFacilityE> getSportFacilities() {
        sportFacilities = getSportFacilitiyService().getAllSportsFacilities();
        sportFacilities = Sorting.sortSportsFacilities(sportFacilities);
        return sportFacilities;
    }

    public void setSportFacilities(List<SportFacilityE> sportFacilities) {
        this.sportFacilities = sportFacilities;
    }

    public SportFacilityE getSelectedSportFacility() {
        if(selectedSportFacility == null) {
            selectedSportFacility = getSportFacilities().get(0);
        }
        return selectedSportFacility;
    }

    public void setSelectedSportFacility(SportFacilityE selectedSportFacility) {
        this.selectedSportFacility = selectedSportFacility;
    }

    public SportsFacilitiesService getSportFacilitiyService() {
        return sportFacilitiyService;
    }

    public void setSportFacilitiyService(SportsFacilitiesService sportFacilitiyService) {
        this.sportFacilitiyService = sportFacilitiyService;
    }
}

web/admin/administration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <f:view contentType="text/html" id="fview" locale="#{language.locale}">

        <h:head>
            <title>#{administration['admincenter']}</title>

            <style type="text/css">
                .dialogEditDetails tr, .dialogEditDetails td {
                    border: none;
                }
                .adminHeader{
                    font-size: 24px;
                    text-align: center;
                    margin-left: 10px;
                }
                .ui-tabs.ui-tabs-left > .ui-tabs-nav li{
                   border-right: 1px solid #000000 !important;
                   border-top-right-radius: 3px;
                   border-bottom-right-radius: 3px;
                }                
            </style>
        </h:head>
        <h:body>

            <p:layout fullPage="true" >
                <p:layoutUnit id="top" gutter="1" position="north" size="50">
                    <h:outputText styleClass="adminHeader" value="#{administration['text.administration']}"/>
                </p:layoutUnit>

                <p:layoutUnit id="bottom" position="south" size="60">
                    <h:link value="#{administration['link.gohome']}" outcome="pretty:home" 
                            style="float: left; margin-left:10px;" />
                </p:layoutUnit>

                <p:layoutUnit id="center" position="center">    
                    
                    <p:tabView id="tabView" dynamic="true" cache="false" orientation="left"> 

                        <p:tab id="tba1" title="#{administration['tab.sportfacility']}">  
                            <ui:include src="sportfacility.xhtml" />                            
                        </p:tab>  

                        <p:tab id="tab2" title="#{administration['tab.sports']}">  
                            <ui:include src="sports.xhtml" />                               
                        </p:tab> 

                        <p:tab id="tab3" title="#{administration['tab.reservations']}">  
                            <ui:include src="reservation.xhtml" />                                
                        </p:tab>  

                        <p:tab id="tab4" title="#{administration['tab.users']}">  
                            <ui:include src="user.xhtml" />                                
                        </p:tab>  

                    </p:tabView>                    

                </p:layoutUnit>

            </p:layout>


        </h:body>

    </f:view>
</html>

web/admin/reservation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets">

    <p:panel header="#{administration['reservation.header.reservations']}">
        <h:form id="reservationDataTable">  
            <p:messages id="messagesR"/>
                       
                <p:dataTable id="dataTable" var="reserv" value="#{adminReservations.allReservations}"
                             paginator="true" rows="10" lazy="true" paginatorPosition="bottom"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15" style="width: 100%;">

                    <p:column>  
                        <f:facet name="header">  
                            <h:outputText value="#{administration['reservation.table.delete']}" />  
                        </f:facet>  
                        <p:commandButton id="deleteRbutton" icon="ui-icon-trash" 
                                         ajax="true"
                                         action="#{adminReservations.deleteReservation()}" 
                                         update="dataTable, :tabView:reservationDataTable:messagesR"
                                         title="#{administration['reservation.button.title.delete']}">  
                            <f:setPropertyActionListener value="#{reserv}" 
                                                         target="#{adminReservations.currentReservation}" />  
                        </p:commandButton>                       
                    </p:column> 

                    <p:column id="modelHeader" sortBy="#{reserv.startDate}">  
                        <f:facet name="header">  
                            <h:outputText value="#{administration['reservation.table.startdate']}" />  
                        </f:facet>  
                        <h:outputText value="#{reserv.startDate}" />  
                    </p:column>  

                    <p:column sortBy="#{reserv.endDate}">  
                        <f:facet name="header">  
                            <h:outputText value="#{administration['reservation.table.enddate']}" />  
                        </f:facet>  
                        <h:outputText value="#{reserv.endDate}" />  
                    </p:column>  

                    <p:column sortBy="#{reserv.title}" filterBy="#{reserv.title}">  
                        <f:facet name="header">  
                            <h:outputText value="#{administration['reservation.table.title']}" />  
                        </f:facet>  
                        <h:outputText value="#{reserv.title}" />  
                    </p:column>  

                    <p:column sortBy="#{reserv.sportFacility.name}" filterBy="#{reserv.sportFacility.name}">  
                        <f:facet name="header">  
                            <h:outputText value="#{administration['reservation.table.sportfacilityname']}" />  
                        </f:facet>  
                        <h:outputText value="#{reserv.sportFacility.name}" />  
                    </p:column>  

                    <p:column sortBy="#{reserv.sport.name}" filterBy="#{reserv.sport.name}">  
                        <f:facet name="header">  
                            <h:outputText value="#{administration['reservation.table.sportname']}" />  
                        </f:facet>  
                        <h:outputText value="#{reserv.sport.name}" />  
                    </p:column> 

                    <p:column sortBy="#{reserv.userE.email}" filterBy="#{reserv.userE.email}">  
                        <f:facet name="header">  
                            <h:outputText value="#{administration['reservation.table.useremail']}" />  
                        </f:facet>  
                        <h:outputText value="#{reserv.userE.email}" />  
                    </p:column> 
                </p:dataTable>   
            
        </h:form>  
    </p:panel>


</ui:composition>

web/admin/sports.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core">

    <p:panel header="#{administration['sport.header.removeedit']}">         
        <h:form id="formDLsports"> 
            <p:messages id="messagesDLSport"/>
            <h:panelGrid columns="1" cellpadding="10">  
                <p:dataList value="#{adminSportAndSfBean.allSports}" var="asport" id="sports"  
                            paginator="true" rows="15"  
                            paginatorTemplate="{PreviousPageLink} {CurrentPageReport} {NextPageLink} {RowsPerPageDropdown}"  
                            rowsPerPageTemplate="15,20,30" type="none">  

                    <!-- Button pre odstranenie sportu -->
                    <p:commandButton id="deleteSbutton" icon="ui-icon-trash" 
                                     ajax="true"
                                     action="#{adminSportAndSfBean.deleteSport}" 
                                     update="sports, :tabView:formDLsports:messagesDLSport"
                                     title="#{administration['sport.button.title.delete']}">  
                        <f:setPropertyActionListener value="#{asport}" target="#{adminSportAndSfBean.currentSport}" />  
                    </p:commandButton>  

                    <!-- Button pre upravu udajov sportoviska -->
                    <p:commandButton id="editSbutton"
                                     ajax="true"
                                     icon="ui-icon-edit" 
                                     oncomplete="sdetail.show()" 
                                     update=":tabView:formsportdetail" 
                                     title="#{administration['sport.button.title.edit']}">  
                        <f:setPropertyActionListener value="#{asport}" 
                                                     target="#{adminSportAndSfBean.currentSport}" />  
                    </p:commandButton>
                    
                    <h:outputText value="#{asport.name}" style="margin-left:10px" />
                    <br />  

                </p:dataList>
            </h:panelGrid>  
        </h:form>             
    </p:panel>
    
    <p:dialog header="#{administration['sport.dialog.header.edit']}" widgetVar="sdetail" modal="false" resizable="false" showEffect="fade">         
        <h:form id="formsportdetail">     
            <p:messages id="messagesSport"/>
            <p:outputPanel id="sdetailpanel" layout="block">  
                <h:panelGrid  columns="2" cellpadding="5">  

                    <h:outputLabel for="sname" value="#{administration['sport.dialog.label.name']}" />  
                    <p:inputText id="sname" 
                                 requiredMessage="#{administration['sport.dialog.input.required.name']}"                                            
                                 value="#{adminSportAndSfBean.currentSport.name}" 
                                 required="true"
                                 validator="#{adminSportAndSfBean.validateSportName}"
                                 /> 
                    
                    <p:commandButton value="#{administration['sport.dialog.button.save']}" 
                                     action="#{adminSportAndSfBean.saveChangesToSport}" 
                                     update=":tabView:formDLsports:sports,:tabView:formsportdetail:messagesSport"                                      
                                     oncomplete="if (!args.validationFailed) {sdetail.hide();}"/>
                    <p:commandButton value="#{administration['sport.dialog.button.cancel']}" 
                                     onclick="sdetail.hide()" />
                </h:panelGrid>  
            </p:outputPanel>  
        </h:form> 
    </p:dialog> 
    
    <p:panel header="#{administration['sport.header.new']}">  
        <h:form id="formadds"> 
            <p:messages id="messagesnewsport"/>
            <h:panelGrid columns="2">                                  
                <h:outputLabel for="sportnameinput" value="#{administration['sport.dialog.label.name']}" />  
                <p:inputText id="sportnameinput" 
                             requiredMessage="#{administration['sport.dialog.input.required.name']}"                                            
                             value="#{adminSportAndSfBean.newSportName}" 
                             required="true"
                             validator="#{adminSportAndSfBean.validateSportName}"
                             >  

                </p:inputText>   
            </h:panelGrid>              
            <!-- Button pre vytvorenie noveho sportoviska s danymi sportmi -->
            <p:commandButton value="#{administration['sport.button.new']}" 
                             actionListener="#{adminSportAndSfBean.saveSport}" 
                             update=":tabView:formDLsports:sports, :tabView:formadds:messagesnewsport" 
                             id="addSportButton"/>  
        </h:form> 
    </p:panel>

</ui:composition>

web/admin/user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets">

        
    <p:panel header="#{administration['user.header.permission']}">    
        <p:messages id="msg"/>
        <h:form id="formsearchuser"> 
            <h:panelGrid columns="3" cellpadding="10">  

                <h:outputLabel for="finduserinput" value="#{administration['user.label.emailid']}" />
                <p:inputText id="finduserinput" 
                             requiredMessage="#{administration['user.input.required.emailid']}"                                            
                             value="#{adminUserBean.searchString}" 
                             required="true"/> 

                <p:commandButton value="#{administration['user.button.find']}" 
                                 ajax="true"
                                 actionListener="#{adminUserBean.searchUser}" 
                                 update=":tabView:formsetadmin:foundeduserdisplay,:tabView:msg" 
                                 id="searchUserButton"/> 
            </h:panelGrid>
        </h:form> 
        <h:form id="formsetadmin"> 
            <p:outputPanel id="foundeduserdisplay">
                <h:panelGrid columns="3" 
                             cellpadding="10" 
                             rendered="#{adminUserBean.renderPanelWithResults}"> 
                    <h:outputText id="foundeduserout"
                                  escape="false"
                                  value="#{adminUserBean.foundUser.email}" /> 

                    <p:selectBooleanCheckbox  id="isAdminCheckbox"  value="#{adminUserBean.foundUser.admin}">  
                        <p:ajax update=":tabView:msg, :tabView:alladminsDL" listener="#{adminUserBean.changeAdminPermission}"/>  
                    </p:selectBooleanCheckbox>  
                    
                    <h:outputText value="#{administration['user.founded.admin']}" />                    
                </h:panelGrid>
            </p:outputPanel>
        </h:form> 

    </p:panel>
    
    <p:panel header="#{administration['user.header.administrators']}">  
        <h:panelGrid columns="1" cellpadding="10">
            <p:dataList value="#{adminUserBean.allAdmins}" var="alladmins" id="alladminsDL"  
                        paginator="true" rows="5"  
                        paginatorTemplate="{PreviousPageLink} {CurrentPageReport} {NextPageLink} {RowsPerPageDropdown}"  
                        rowsPerPageTemplate="10,15,20" paginatorPosition="bottom" type="none">  

                <h:outputText value="#{alladmins.email}" style="margin-left:10px" />
                <br />  
            </p:dataList>
        </h:panelGrid>  
    </p:panel>   

</ui:composition>